services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: appdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: password
    volumes:
      - ./mysql:/scripts
    ports:
      - "3306:3306"

  api:
    build:
      context: ./node-api
      dockerfile: ../docker/node-api/Dockerfile
    volumes:
      - ./node-api:/app
    ports:
      - "3001:3001"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/frontend/Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - api
